# ATHLETIKS.IO
USUARIO_GIRONA = "sisterhoodrunningclub@gmail.com"
PASSWORD_GIRONA = "SHcarlota23"

USUARIO_ELCHE = "evamartinmoreno9@gmail.com"
PASSWORD_ELCHE = "SHeva2024"

# INSTAGRAM
IG_ACCESS_TOKEN = "EAAJg1EXrT80BO42KgisKKLP5gqsKmtn6VUsL7PZCnra3uZCDtlMfTTvW4Lsxlq0PWNlyz1hMpL2rZB2k3QZCkpNSJVe3UATadn7725xc4w869ZCqQ4Uj20mqjjb4fWR81i9LrAxmkvzQqgdvW0oAcjwmSZC9b53s7jHxPQ4vSUujRgBeYOXgZDZD"
IG_USER_ID = "17841458252704780"
IG_USERNAME = "sisterhoodrunningclub"
IG_PASSWORD = "SHcarlota23"
TARGET_PROFILE = "sisterhoodrunningclub"
